import type { Metadata } from "next";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://humna.dev";

export const siteConfig = {
  name: "Humna Sadia",
  title: "Humna Sadia — Software Engineer",
  description:
    "Computer Science undergraduate at FAST-NUCES building cross-platform applications, AI systems, and high-performance software. Selected work in React Native, Firebase, CUDA, and machine learning.",
  url: SITE_URL,
  ogImage: `${SITE_URL}/opengraph-image`, // generated by app/opengraph-image.tsx
  twitter: "@humnasadia",                  // update or remove
  author: { name: "Humna Sadia", url: SITE_URL },
  keywords: [
    "Humna Sadia",
    "Software Engineer",
    "FAST-NUCES",
    "React Native",
    "Firebase",
    "CUDA",
    "Machine Learning",
    "Mobile Developer",
    "Frontend Engineer",
    "Islamabad",
  ],
} as const;

export const defaultMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: siteConfig.title, template: `%s — ${siteConfig.name}` },
  description: siteConfig.description,
  keywords: [...siteConfig.keywords],
  authors: [siteConfig.author],
  creator: siteConfig.name,
  publisher: siteConfig.name,

  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.title,
    description: siteConfig.description,
    images: [{ url: siteConfig.ogImage, width: 1200, height: 630, alt: siteConfig.title }],
  },

  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: siteConfig.twitter,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  icons: {
    icon: [
      { url: "/favicon/favicon.ico" },
      { url: "/favicon/icon-32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/favicon/apple-touch-icon.png", sizes: "180x180" }],
  },

  manifest: "/manifest.webmanifest",

  alternates: {
    canonical: siteConfig.url,
  },

  category: "technology",
};

/** Person JSON-LD — improves Google Knowledge Panel + AI search citations */
export function personSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name: siteConfig.name,
    url: siteConfig.url,
    image: `${siteConfig.url}/og/humna.jpg`,
    jobTitle: "Software Engineer",
    description: siteConfig.description,
    alumniOf: {
      "@type": "CollegeOrUniversity",
      name: "FAST National University of Computer and Emerging Sciences",
    },
    sameAs: [
      "https://github.com/Hhumna",
      "https://www.linkedin.com/in/humna-sadia-936b11315/",
    ],
    knowsAbout: [
      "Software Engineering",
      "Mobile Development",
      "Machine Learning",
      "Parallel Computing",
      "System Design",
    ],
  };
}
